apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-collor
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/jorgetrc/k8s-workflow.git
    targetRevision: main
    path: base
  destination:
    server: https://kubernetes.default.svc
    namespace: image-collor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
