apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yml
- deployment.yml
- service.yml
images:
- name: jldevops01/image-collor
  newName: jldevops01/image-collor
  newTag: v1.0.8
