apiVersion: v1
kind: Service
metadata:
  name: image-collor-service
  labels:
    app: image-collor
  namespace: image-collor
spec:
  type: ClusterIP 
  selector:
    app: image-collor 
  ports:
    - protocol: TCP
      port: 80 
      targetPort: 80
